module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      primary: "#0015BC",
      secondary: "#FF0000",
      other: "#22c74e",
      white: "white",
      black: "black",
      selectBg: "white",
      selectBorder: "#e3edfc",
      selectBorderActive: "#6b96db",
      blue: "#2563EB",
      red: "#EF4444",
      lightGreyText: "#4B5563",
      blueGray300: "#90a4ae",
      blueGray600: "#546e7a",
      blue500: "#2196f3",
      footerBackground: "#3F3F46",
      footerText: "white",
      tooltipBack: "#e6f7f4",
    },
    extend: {},
  },
  plugins: [],
};
