/* Organization Actions */
export const ADD_ORGANIZATION_PERIOD = "ADD_ORGANIZATION_PERIOD";
export const REMOVE_ALL_ORGANIZATION_PERIODS =
  "REMOVE_ALL_ORGANIZATION_PERIODS";

/* Politician Actions */
